### ISSUE TITLE
analogue_alignment seems to be gone

### ISSUE THREAD

**Issue by daveminh** [CCBatIIT/Bridgeport#15]
I was using `from Bridgeport.utils.bp_utils import analogue_alignment` but this doesn't work and I don't see the function in `from Bridgeport.utils.utils` either.

**Comment by davidcooper7** [comment]
The script `Bridgeport.utils.bp_utils` has changed to `Bridgeport.utils.utils` and the `analogue_alignment` method has been deprecated. The `Ligand` and `Analogue` classes now support analogue and ligand generation. For a tutorial on how to use these new tools, please refer to [https://github.com/CCBatIIT/Bridgeport/blob/main/Ligand/test.ipynb](url)
