### ISSUE TITLE
More robust input to pdbfixer

### ISSUE THREAD

**Issue by daveminh** [CCBatIIT/Bridgeport#16]
I suggest trim_env can set the CRYST1 line before creating the environment. Also it shouldn't require a CRYST1 line in the file. Finally there was a bug with trim that left a partial water block. I have no idea why the partial water block happens, so I skipped the trimming.

# Adds a CRYST1 line so that trim_env doesn't complain
with open(pp.H_pdb,'r') as F:
  dat = F.read()
with open(pp.H_pdb,'w') as F:
  F.write('CRYST1\n')
  F.write(dat)

from Bridgeport.utils.bp_utils import trim_env
trim_env(pp.H_pdb) # Measures appropriate box size

#Create Environment
print(datetime.now().strftime("%m/%d/%Y %H:%M:%S") + '//Creating environment with pdbfixer', flush=True)
pp._run_PDBFixer(mode=pp.env, padding=1.5, ionicStrength=pp.ion)

# Check completion
if os.path.exists(pp.env_pdb):
    print(datetime.now().strftime("%m/%d/%Y %H:%M:%S") + '//Output written to:', pp.env_pdb, flush=True)

# Trim 
print(datetime.now().strftime("%m/%d/%Y %H:%M:%S") + '//Trimming', pp.env_pdb, 'with padding of 15 Angstroms.', flush=True)
trim_env(pp.env_pdb, 15)

**Comment by davidcooper7** [comment]
The `Bridgeport.utils.trim_env` method has been update with a more robust way to handle various naming schemes for HOH atoms. Please reopen this issue if errors continue.
