### ISSUE TITLE
Position Match error

### ISSUE THREAD

**Issue by Talha-2233** [CCBatIIT/Bridgeport#17]
Error:
<img width="893" alt="isuse" src="https://github.com/user-attachments/assets/6d7c410a-6244-4532-a3e0-eece11f016b1">

input .json file:

[compound_1.json](https://github.com/user-attachments/files/17653481/compound_1.json)

**Comment by davidcooper7** [comment]
@Talha-2233 please provide the additional input files to allow us to test this issue. From your input.json, it looks like we will need:

```
/ocean/projects/mcb160011p/mtalib/Bridgeport/B2A/crystal_pdb/modified_protein.pdb
/ocean/projects/mcb160011p/mtalib/B2A/OPM/OPM.pdb
/ocean/projects/mcb160011p/mtalib/Bridgeport/B2A/fasta/ADRB2.fasta
```

**Comment by Talha-2233** [comment]
Hi,
I have attached the required files.

Thanks
Regards

**Comment by davidcooper7** [comment]
Please see #19
