### ISSUE TITLE
IndexError in _trim_env due to out of bounds atoms index during environment setup

### ISSUE THREAD

**Issue by MKStanisz** [CCBatIIT/Bridgeport#19]
![image](https://github.com/user-attachments/assets/2351fe0b-44d6-46ff-9499-575b379403e4)

.json file: [interactive.json](https://github.com/user-attachments/files/17689287/interactive.json)

**Comment by davidcooper7** [comment]
Next time, please provide the appropriate input files. See [https://github.com/CCBatIIT/Bridgeport/issues/17](url)

I was able to collect the appropriate input, however. The error should be resolved. Thanks.
