### ISSUE TITLE
Parameterizing Peptide Ligands with OpenFF

### ISSUE THREAD

**Issue by josephdepaoloboisvert** [CCBatIIT/Bridgeport#2]
Parameterizing the entire peptide ligand with OpenFF takes far too long.
The next workaround to try is to parameterize only the nonstandard Amino Acid with Openff, and the rest with AMBERFF14SB

**Comment by davidcooper7** [comment]
This issue has still not been handled. When an appropriate case comes along where Bridgeport needs to properly handle this, then we will address this.
