### ISSUE TITLE
_trim_env IndexError

### ISSUE THREAD

**Issue by MKStanisz** [CCBatIIT/Bridgeport#23]
I still seem to be experiencing the IndexError after commit 95365b5

Error: [D2R_out.txt](https://github.com/user-attachments/files/17742049/D2R_out.txt)

Inputs
- [paliperidone.json](https://github.com/user-attachments/files/17742055/paliperidone.json)
- [6cm4_pdb.txt](https://github.com/user-attachments/files/17742061/6cm4_pdb.txt)
- [AFD2DR_alignment_refpdb.txt](https://github.com/user-attachments/files/17742086/AFD2DR_alignment_refpdb.txt)
- [ligand_paliperidone_pdb.txt](https://github.com/user-attachments/files/17742131/ligand_paliperidone_pdb.txt)

This is the last written output before the error occurs: 
[paliperidone_H_pdb.txt](https://github.com/user-attachments/files/17742122/paliperidone_H_pdb.txt)

Let me know if there's anymore files that you require.

**Comment by MKStanisz** [comment]
Sorry, just read https://github.com/CCBatIIT/Bridgeport/issues/17, here's the fasta file: [D2DR_fasta.txt](https://github.com/user-attachments/files/17742200/D2DR_fasta.txt)

**Comment by davidcooper7** [comment]
This, as well as continued issues from #19 #17 should be fixed with 4a555a5f21c1511ca91d39fba185f9634824f454
