### ISSUE TITLE
Analogue Jobs

### ISSUE THREAD

**Issue by aimankhan131** [CCBatIIT/Bridgeport#24]
Hello David
I submitted analogue jobs IHCH-7120, IHCH-7078, and IHCH-7089 AND DOI analogues that I need to redo again. Only one analogue job, IHCH-7120, ran successfully yesterday. And all other 3 gave this error, as mentioned in the screenshots attached below.
Thankyou.
![image](https://github.com/user-attachments/assets/4838c73d-edd1-462b-aae4-f1b92bf4fba2)
![image](https://github.com/user-attachments/assets/e285edaf-47a7-47f2-8743-c759a0d42935)
![image](https://github.com/user-attachments/assets/5851eae7-0a0b-4e82-852b-256d0f7bfc75)

**Comment by davidcooper7** [comment]
See #23
