### ISSUE TITLE
Error parsing atom numbers in pdb

### ISSUE THREAD

**Issue by MKStanisz** [CCBatIIT/Bridgeport#26]
Using https://github.com/CCBatIIT/Bridgeport/commit/017e5ca5fc440ed1d369da629e40da888bbd513c I am now able to progress past the _trim_env index error, however, I am now receiving an OverFlowError: Need to parse atom number using non-decimal residues modes. I'll provide the output files as well as the generated PDB file.

[D2R_3.out.txt](https://github.com/user-attachments/files/17781747/D2R_3.out.txt)
[paliperidone_pdb.txt](https://github.com/user-attachments/files/17781748/paliperidone_pdb.txt)

**Comment by davidcooper7** [comment]
It looks like the .pdb is too big resulting in too many atoms with a naming scheme that is unconventional. We're currently experimenting with a fix.

**Comment by davidcooper7** [comment]
The commit f31a912dd9e3205fcee2dc7fd86e4cefd70053c6 should fix this issue. I tried with your test case. Changes to how the topology was read with mdtraj was necessary for larger systems.
