### ISSUE TITLE
ModellerError: Missing Protein Sequence in Alignment File for analogue 25-N-NBI

### ISSUE THREAD

**Issue by aimankhan131** [CCBatIIT/Bridgeport#28]
Hi David,

I'm encountering an error with my analogue 25-N-NBI. Could you please check it out?

Thankyou.

[25-N-NBI.json](https://github.com/user-attachments/files/17876393/25-N-NBI.json)
[BRIDGEPORT.26912228.v012.out.txt](https://github.com/user-attachments/files/17876406/BRIDGEPORT.26912228.v012.out.txt)

**Comment by davidcooper7** [comment]
I cannot recreate this error using interactive.ipynb. Can you please send the .fasta file @aimankhan131? Also, I would try 
[interactive.zip](https://github.com/user-attachments/files/17895883/interactive.zip)
regenerating the .fasta file with interactive.ipynb, and then submitting the batch job again.

**Comment by aimankhan131** [comment]
Sure, here it is,
[5HT2A.txt](https://github.com/user-attachments/files/17896219/5HT2A.txt)
 @davidcooper7
